version: 2.1

jobs:
    build:
        docker:
          - image: circleci/openjdk:11-jdk
        working_directory: ~/repo

        environment:
          MAVEN_OPTS: -Xmx3200m

        steps:
          - checkout
          - restore_cache:
              keys:
                - v1-dependencies-{{ checksum "pom.xml" }}

          - run: mvn install -DskipTests

          - run: mvn dependency:gooffline

          - save_cache:
              paths:
                - ~/.m2
              key: v1-dependencies-{{ checksum "pom.xml" }}

          - run: mvn integration-test
